<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
        $this->load->model('Usuario_model');
        $this->load->model('Prueba_model');
        
        $this->session_data = $this->session->userdata('logged_in');
    }

    function index()
    {
        if ($this->session->userdata('logged_in')) {

            $session_data = $this->session->userdata('logged_in');

            //if($session_data['tipousuario_id']==1){        
                    
                $usuario_id = $session_data['usuario_id'];
                
                $data['empresa'] = $this->Empresa_model->get_empresa(1);
                $data['usuario'] = $this->Usuario_model->get_usuario($usuario_id);

                // Cantidad pruebas registradas
                $sql = "select count(*) as cantidad from prueba 
                        where date(prueba_fecharegistro) = date(now())";
                $data['pruebas_registradas'] = $this->Prueba_model->consultar($sql);

                // Cantidad pruebas registradas
                $sql = "select count(*) as cantidad from paciente";
                $data['pacientes'] = $this->Prueba_model->consultar($sql);

                // Cantidad pruebas registradas
                $sql = "select count(*) as cantidad from prueba 
                        where estado_id <> 3"; //pruebas sin entregar
                $data['pruebas_pendientes'] = $this->Prueba_model->consultar($sql);


                $sql = "select r.*, p.*, u.*, t.*, e.*
                        from prueba r
                        left join paciente p on p.paciente_id = r.paciente_id
                        left join usuario u on u.usuario_id = r.usuario_id
                        left join tipo_prueba t on t.tipoprueba_id = r.tipoprueba_id
                        left join estado e on e.estado_id = r.estado_id
                        where r.estado_id = 1 order by r.prueba_id desc";
                ///echo $sql;
                $data['pruebas'] = $this->Prueba_model->consultar($sql);


                // Suma de ingresos ver 1.0
                $sql = "select if(sum(acuenta+saldo)>0,sum(acuenta+saldo),0) as ingresos
                        from
                        (
                        (SELECT 
                          if(sum(prueba_acuenta)>0,sum(prueba_acuenta),0) AS acuenta, 0 as saldo
                        FROM prueba
                        WHERE date(prueba_fechacuenta) = date(now())
                        )

                        union  

                        ( SELECT 0 as acuenta,
                          if(sum(prueba_saldo)>0,sum(prueba_saldo),0) AS saldo
                                FROM
                          prueba WHERE
                          date(prueba_fechasaldo) = date(now())) 
                        ) as t1"; //pruebas sin entregar
                $data['ingresos'] = $this->Prueba_model->consultar($sql);

                $data['_view'] = 'dashboard';
                $this->load->view('layouts/main',$data);
                
                
            //}else{
            //        $url = base_url("login");
            //       header("Location: .$url");
            //        die();
            //    }
                
        } else {redirect('login', 'refresh'); }
    }
}
