<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
        $this->load->model('Usuario_model');
    }

    function index()
    {
        $data['empresa'] = $this->Empresa_model->get_empresa(1);
        $data['usuario'] = $this->Usuario_model->get_usuario(1);
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
