<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Extencion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get extencion by extencion_id
     */
    function get_extencion($extencion_id)
    {
        $extencion = $this->db->query("
            SELECT
                *

            FROM
                `extencion`

            WHERE
                `extencion_id` = ?
        ",array($extencion_id))->row_array();

        return $extencion;
    }
    
    /*
     * Get all extencion count
     */
    function get_all_extencion_count()
    {
        $extencion = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `extencion`
        ")->row_array();

        return $extencion['count'];
    }
        
    /*
     * Get all extencion
     */
    function get_all_extencion($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $extencion = $this->db->query("
            SELECT
                *

            FROM
                `extencion`

            WHERE
                1 = 1

            ORDER BY `extencion_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $extencion;
    }
        
    /*
     * function to add new extencion
     */
    function add_extencion($params)
    {
        $this->db->insert('extencion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update extencion
     */
    function update_extencion($extencion_id,$params)
    {
        $this->db->where('extencion_id',$extencion_id);
        return $this->db->update('extencion',$params);
    }
    
    /*
     * function to delete extencion
     */
    function delete_extencion($extencion_id)
    {
        return $this->db->delete('extencion',array('extencion_id'=>$extencion_id));
    }
}
