<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prueba_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prueba by prueba_id
     */
    function get_prueba($prueba_id)
    {
        $prueba = $this->db->query("
            SELECT
                *

            FROM
                `prueba`

            WHERE
                `prueba_id` = ?
        ",array($prueba_id))->row_array();

        return $prueba;
    }
    
    /*
     * Get all prueba count
     */
    function get_all_prueba_count()
    {
        $prueba = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `prueba`
        ")->row_array();

        return $prueba['count'];
    }
        
    /*
     * Get all prueba
     */
    function get_all_prueba($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $prueba = $this->db->query("
            SELECT
                *

            FROM
                `prueba`

            WHERE
                1 = 1

            ORDER BY `prueba_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $prueba;
    }
        
    /*
     * function to add new prueba
     */
    function add_prueba($params)
    {
        $this->db->insert('prueba',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prueba
     */
    function update_prueba($prueba_id,$params)
    {
        $this->db->where('prueba_id',$prueba_id);
        return $this->db->update('prueba',$params);
    }
    
    /*
     * function to delete prueba
     */
    function delete_prueba($prueba_id)
    {
        return $this->db->delete('prueba',array('prueba_id'=>$prueba_id));
    }
}
