<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prueba_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prueba by prueba_id
     */
    function get_prueba($prueba_id)
    {
        $sql = "select r.*, p.*, u.*, t.*,g.*
                from prueba r
                left join paciente p on p.paciente_id = r.paciente_id
                left join genero g on p.genero_id = g.genero_id
                left join usuario u on u.usuario_id = r.usuario_id
                left join tipo_prueba t on t.tipoprueba_id = r.tipoprueba_id 
                where r.prueba_id = ".$prueba_id;
        
        $prueba = $this->db->query($sql)->row_array();

        return $prueba;
    }
    
    
    function get_prueba_md5($prueba_id)
    {
        $sql = "select r.*, p.*, u.*, t.*,g.*
                from prueba r
                left join paciente p on p.paciente_id = r.paciente_id
                left join genero g on p.genero_id = g.genero_id
                left join usuario u on u.usuario_id = r.usuario_id
                left join tipo_prueba t on t.tipoprueba_id = r.tipoprueba_id 
                where md5(r.prueba_id) = '".$prueba_id."'";
        
        $prueba = $this->db->query($sql)->row_array();

        return $prueba;
    }
    
    
    function get_pruebas()
    {
        $sql = "select r.*, p.*, u.*, t.*, e.*
                from prueba r
                left join paciente p on p.paciente_id = r.paciente_id
                left join usuario u on u.usuario_id = r.usuario_id
                left join tipo_prueba t on t.tipoprueba_id = r.tipoprueba_id
                left join estado e on e.estado_id = r.estado_id
                order by r.prueba_id desc";
        
        $prueba = $this->db->query($sql)->result_array();
        return $prueba;
    }
    
    
    
    /*
     * Get all prueba count
     */
    function get_all_prueba_count()
    {
        $prueba = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `prueba`
        ")->row_array();

        return $prueba['count'];
    }
        
    /*
     * Get all prueba
     */
    function get_all_prueba($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $prueba = $this->db->query("
            SELECT
                *

            FROM
                `prueba`

            WHERE
                1 = 1

            ORDER BY `prueba_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $prueba;
    }
        
    /*
     * function to add new prueba
     */
    function add_prueba($params)
    {
        $this->db->insert('prueba',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prueba
     */
    function update_prueba($prueba_id,$params)
    {
        $this->db->where('prueba_id',$prueba_id);
        return $this->db->update('prueba',$params);
    }
    
    /*
     * function to delete prueba
     */
    function delete_prueba($prueba_id)
    {
        return $this->db->delete('prueba',array('prueba_id'=>$prueba_id));
    }
    
    function consultar($sql){
        
        return $this->db->query($sql)->result_array();
        
    }
    
    function ejecutar($sql){
        
        return $this->db->query($sql);
        
    }
}
