<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_prueba_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_prueba by tipoprueba_id
     */
    function get_tipo_prueba($tipoprueba_id)
    {
        $tipo_prueba = $this->db->query("
            SELECT
                *

            FROM
                `tipo_prueba`

            WHERE
                `tipoprueba_id` = ?
        ",array($tipoprueba_id))->row_array();

        return $tipo_prueba;
    }
    
    /*
     * Get all tipo_prueba count
     */
    function get_all_tipo_prueba_count()
    {
        $tipo_prueba = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `tipo_prueba`
        ")->row_array();

        return $tipo_prueba['count'];
    }
        
    /*
     * Get all tipo_prueba
     */
    function get_all_tipo_prueba($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $tipo_prueba = $this->db->query("
            SELECT
                *

            FROM
                `tipo_prueba`

            WHERE
                1 = 1

            ORDER BY `tipoprueba_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $tipo_prueba;
    }
        
    /*
     * function to add new tipo_prueba
     */
    function add_tipo_prueba($params)
    {
        $this->db->insert('tipo_prueba',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_prueba
     */
    function update_tipo_prueba($tipoprueba_id,$params)
    {
        $this->db->where('tipoprueba_id',$tipoprueba_id);
        return $this->db->update('tipo_prueba',$params);
    }
    
    /*
     * function to delete tipo_prueba
     */
    function delete_tipo_prueba($tipoprueba_id)
    {
        return $this->db->delete('tipo_prueba',array('tipoprueba_id'=>$tipoprueba_id));
    }
}
