<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by usuario_id
     */
    function get_usuario($usuario_id)
    {
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                `usuario_id` = ?
        ",array($usuario_id))->row_array();

        return $usuario;
    }
    
    /*
     * Get all usuario count
     */
    function get_all_usuario_count()
    {
        $usuario = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `usuario`
        ")->row_array();

        return $usuario['count'];
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                1 = 1

            ORDER BY `usuario_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $usuario;
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($usuario_id,$params)
    {
        $this->db->where('usuario_id',$usuario_id);
        return $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($usuario_id)
    {
        return $this->db->delete('usuario',array('usuario_id'=>$usuario_id));
    }
}
